config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  post 'posts/create', as: 'posts'
  post 'posts/repost/:id', to: 'posts#repost', as: 'repost'
  get 'likes/:id', to: 'likes#to_like', as: 'like'
  delete 'likes/:id', to: 'likes#to_dislike', as: 'dislike'
  get 'posts/likes/:id', to: 'posts#show', as: 'post_detail'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :reposts, class_name: "Post", foreign_key: "post_id", dependent: :destroy
  belongs_to :original_post, class_name: "Post", foreign_key: "post_id", optional: true
  
  
  validates :content, presence: :true
  
end

# rails g migration AddRetweetsToTweets tweet:references

# belongs_to :original_tweet, class_name: "Tweet", foregin_key: "tweet_id", optional: true
# has_many :retweets, class_name: "Tweet", foreign_key: "tweet_id", dependent: :destroy

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
    devise_parameter_sanitizer.permit(:update, keys: [:name, :photo])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def to_like
    post = Post.find(params[:id])
    flash[:notice] = "No puedes dar dos likes sobre el mismo post" if post.likes.pluck(:user_id).include?(current_user.id)
    new_like = Like.create(post: post, user: current_user)
    redirect_to root_path
  end

  def to_dislike
    post = Post.find(params[:id])
    like = post.likes.find_by(user_id: current_user.id)
    like.destroy
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:q]
      @posts = Post.where('content LIKE ?', "%#{params[:q]}%").order(created_at: :desc).page params[:page]
    else
      @posts = Post.eager_load(:user, :likes).order(created_at: :desc).page params[:page]
    end
    @post = Post.new
    @user_likes = Like.eager_load(:user, :post).where(user: current_user).pluck(:post_id)
  end

  def show
    @post = Post.find(params[:id]) #Encontramos post con cierto id
    @post_likes = @post.likes #encontramos a todos los likes del post []
  end
  

  def create
    @posts = Post.eager_load(:user, :likes).order(created_at: :desc).page params[:page]
    @post = Post.new(content: params[:post][:content])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Wena lo re creaste" }
      else
        format.html {render :index}
      end
    end    
  end

  def repost
    @post = Post.find(params[:id])
    new_post = Post.create(content: @post.content, user: current_user)
    @post.reposts << new_post
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def hashtag(content)
    hash = content.split(" ")
    words = []
      hash.each do |twt|
        if twt.start_with?("#")
          twt = link_to twt, controller: "posts", q: twt
        end
        words.push(twt)
      end
      raw words.join(" ")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container pt-5 mt-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
  <%= form_with(model: @post, local: true) do |f| %>
    <% if @post.errors.any? %>
      <div id = 'error_explanation'>
        <h2>Este Post no se pudo crear por las siguientes razones</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, placeholder: 'Mandate un post', class: 'form-control' %>
    </div>
    <div class = 'actions'>
      <%= f.submit %>
    </div>
  <% end %>

app/views/posts/_next_page_btn.html.erb
<button class="learn-more">
  <span class="circle" aria-hidden="true">
    <span class="icon arrow"></span>
  </span>
  <span class="button-text"><%= link_to_next_page @posts, 'Ver más', class: 'button-text' %></span>
</button>

app/views/posts/_posts.html.erb
<% @posts.each do |p| %>
  <div class="col-md-4">
    <div class="flip">
      <div class="front" style="background-image: url(<%= p.user.photo%>)">
        <h1 class="text-shadow"><%= p.user.name %></h1>
      </div>
      <div class="back">
        <h2><%= p.user.name %></h2>
        <p><%= hashtag(p.content) %></p>
        <span>
          <%= link_to repost_path(p.id), method: :post do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-recycle" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" />
                <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" transform="rotate(120 12 13)" />
                <path d="M12 17l-2 2l2 2m-2 -2h9a2 2 0 0 0 1.75 -2.75l-.55 -1" transform="rotate(240 12 13)" />
            </svg>
          <% end %>
          <span><%= p.reposts.count %></span>
        </span>
        <span>
          <% if @user_likes.include? p.id %>
            <%= link_to dislike_path(p.id), method: :delete do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-broken" width="28" height="28" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                <path d="M12 7l-2 4l4 3l-2 4v3" />
              </svg>
            <% end %>
          <% else %>
            <%= link_to like_path(p.id) do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="28" height="28" viewBox="0 0 24 24" stroke-width="2" stroke="#ff2825" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M19.5 13.572l-7.5 7.428l-7.5 -7.428m0 0a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
              </svg>
            <% end %>
          <% end %>
        </span>
        <span><%= p.likes.count %></span>
        <% if p.post_id.present? %>
          <h6>
            <span>Reposteado desde el post del usuario: </span>
            <strong>
              <%= p.original_post.user.name %>
            </strong>
          </h6>
        <% end %>
        <%= link_to post_detail_path(p.id) do %>
          <%= distance_of_time_in_words(Time.now, p.created_at) %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_prev_page_btn.html.erb
<button class="learn-more">
  <span class="circle" aria-hidden="true">
    <span class="icon arrow"></span>
  </span>
  <span class="button-text"><%= link_to_prev_page @posts, 'Anterior', class: 'button-text' %></span>
</button>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <div class="container">
    <%= render "form" %>
  </div>
<% end %>

<div class="container-fluid pt-5 mt-5">
  <div class="row">
    <%= render "posts" %>
  </div>
</div>

<div class="container text-left py-5">
  <% if @posts.current_page == 1 %>
    <%= render 'next_page_btn' %>
  <% elsif @posts.total_pages == @posts.current_page %>
    <%= render 'prev_page_btn' %>
  <% else %>
    <%= render 'next_page_btn' %>
    <span>----</span>
    <%= render 'prev_page_btn' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <figure class="snip1344">
    <img src="<%= @post.user.photo%>" alt="profile-sample1" class="background"/><img src="<%= @post.user.photo%>" alt="profile-sample1" class="profile"/>
    <figcaption>
      <h3><%= @post.user.name %><span><%= @post.user.email %></span></h3>
      <div class="icons"><%= @post.content %></div>
    </figcaption>
  </figure>
  <br>
  <hr>
  <h4 class= "py-5">Personas que le dan hado like</h4>
  <div class="row">
    <% @post_likes.each do |pl| %>
      <div class="col-3">
        <%= image_tag pl.user.photo, class: 'img-fluid user_photo' %>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navigation-wrap bg-light start-header start-style">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<nav class="navbar navbar-expand-md navbar-light">
					
						<a class="navbar-brand" href="<%= root_path %>"><img src="https://pbs.twimg.com/profile_images/1774233686/twitter_bird_400x400.png" alt=""></a>	
						
						<%= form_with(url: root_path, method: :get, local: :true, class: 'form-inline my-2 my-lg-0') do  %>
							<%= text_field_tag :q, "", class:'form-control mr-sm-2' %>
							<%= submit_tag("Search", class: 'btn btn-outline-success my-2 my-sm-0') %>
						<% end %>

						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						
						<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav ml-auto py-4 py-md-0">
								<% if user_signed_in? %>
									<li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
										<a class="nav-link" href="#"><%= image_tag current_user.photo, class: 'nav-user-photo' %></a>
									</li>
									<li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
										<a class="nav-link" href="#"><%= current_user.name %></a>
									</li>
								<% end %>
								<li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
									<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
									<div class="dropdown-menu">
                    <% if user_signed_in? %>
                      <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
										  <a class="dropdown-item" href="#">Andate a tu perfil</a>
                      <a class="dropdown-item" href="#">Amigos</a>
                    <% else %>
                      <%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item' %>
                      <%= link_to 'Registrarse', new_user_registration_path, class: 'dropdown-item' %>
                    <% end %>
									</div>
								</li>
							</ul>
						</div>
						
					</nav>		
				</div>
			</div>
		</div>
	</div>